language: csharp
os:
  - linux
before_install:
  - git clone https://github.com/$TRAVIS_REPO_SLUG.git $TRAVIS_REPO_SLUG
  - cd $TRAVIS_REPO_SLUG
  - git checkout -qf $TRAVIS_COMMIT 
mono:
  - latest
dotnet: 1.0.4
dist: trusty
script:
  - ./build.sh
